### ISSUE TITLE
Usage of contentFiles section

### ISSUE THREAD

**Issue by pgrawehr** [NuGet/docs.microsoft.com-nuget.de-de#13]
This should have a full example on the usage of the <contentFiles/> section. With the snippet given, it lacks the relevant information that the <contentFiles/> section must be placed under the <metadata /> section, not besides the <files/> section (at the root level). 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 06a19d7d-253d-f17f-6421-624c9867473d
* Version Independent ID: cc37eb17-f715-080c-7bfc-9eae868d50ba
* Content: [NUSPEC-Dateireferenz für NuGet](https://docs.microsoft.com/de-de/nuget/reference/nuspec#feedback)
* Content Source: [docs/reference/nuspec.md](https://github.com/NuGet/docs.microsoft.com-nuget.de-de/blob/live/docs/reference/nuspec.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by CeciAc** [comment]
Issue moved to [NuGet/docs.microsoft.com-nuget #1351](https://github.com/NuGet/docs.microsoft.com-nuget/issues/1351) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @pgrawehr 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/NuGet/docs.microsoft.com-nuget/issues/1351

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
