### ISSUE TITLE
Invalid xsd reference

### ISSUE THREAD

**Issue by Q-Tec90** [NuGet/docs.microsoft.com-nuget.de-de#17]
Hello,

the xsd reference in the example is invalid. 
Could you please fix that.

**Comment by srvbpigh** [comment]
Hello, @Q-Tec90
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [NuGet/docs.microsoft.com-nuget #1792](https://github.com/NuGet/docs.microsoft.com-nuget/issues/1792) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @Q-Tec90

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/NuGet/docs.microsoft.com-nuget/issues/1792

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi @Q-Tec90
