### ISSUE TITLE
Documentation appears to need updates

### ISSUE THREAD

**Issue by taori** [NuGet/docs.microsoft.com-nuget.de-de#3]
There is no indication about "symbolUrl" - However it is available for package configuration now. I've seen how it is shown during Connect/Build 2018. There should be some samples on how it works / how to get it working as intendend.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 06a19d7d-253d-f17f-6421-624c9867473d
* Version Independent ID: cc37eb17-f715-080c-7bfc-9eae868d50ba
* Content: [NuSpec-Dateireferenz für NuGet](https://docs.microsoft.com/de-de/nuget/reference/nuspec)
* Content Source: [docs/reference/nuspec.md](https://github.com/NuGet/docs.microsoft.com-nuget.de-de/blob/live/docs/reference/nuspec.md)
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by LisandroSu** [comment]
Issue moved to [NuGet/docs.microsoft.com-nuget #1011](https://github.com/NuGet/docs.microsoft.com-nuget/issues/1011) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
Hello, @taori , 
 
Your contribution is much appreciated. Your feedback is related to the original documentation. 
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/NuGet/docs.microsoft.com-nuget/issues/1011. 
 
We truly appreciate your contribution to our articles.  
 
Kind regards, 
Microsoft DOCS International Team
